ARG DEEPSTREAM_VERSION
ARG DEEPSTREAM_DEVEL_IMAGE=nvcr.io/nvidia/deepstream:$DEEPSTREAM_VERSION-triton-multiarch
FROM $DEEPSTREAM_DEVEL_IMAGE
ARG TARGETARCH
ARG DEEPSTREAM_VERSION
ARG OPENCV_VERSION=4.12.0

ARG CMAKE_VER=3.27.7
RUN if [ "$TARGETARCH" = "amd64" ]; then \
      wget -nv -O /tmp/cmake.sh https://github.com/Kitware/CMake/releases/download/v$CMAKE_VER/cmake-$CMAKE_VER-linux-x86_64.sh; \
    else \
      wget -nv -O /tmp/cmake.sh https://github.com/Kitware/CMake/releases/download/v$CMAKE_VER/cmake-$CMAKE_VER-linux-aarch64.sh; \
    fi && \
    sh /tmp/cmake.sh --skip-license --prefix=/usr/local && \
    rm -f /tmp/cmake.sh

COPY libs/opencv/savant /tmp/opencv-savant
COPY utils/build_opencv.sh /tmp/build_opencv.sh
RUN if [ "$DEEPSTREAM_VERSION" = "9.1" ]; then \
      OPENCV_VERSION=4.14.0; \
    fi && \
    export OPENCV_VERSION && \
    bash /tmp/build_opencv.sh /tmp/opencv-savant \
      /tmp/opencv-${OPENCV_VERSION}-${TARGETARCH}-ds${DEEPSTREAM_VERSION}.tar.gz

ENTRYPOINT ["/bin/sh", "-c", "cp /tmp/opencv-*.tar.gz /out"]
