ARG SAVANT_DEEPSTREAM_IMAGE=savant-deepstream:latest
FROM ${SAVANT_DEEPSTREAM_IMAGE}

COPY requirements.txt requirements.txt
RUN python -m pip install -r requirements.txt

# normally you can map a host dir, but if building a self-contained image, use copy
# COPY module module
WORKDIR /opt/savant/src/module

ENTRYPOINT ["./run.py"]
